services:
  db:
    image: mysql:8.0
    container_name: proyectoarduino_db
    environment:
      MYSQL_ROOT_PASSWORD: querido
      MYSQL_DATABASE: proyectoarduino
      MYSQL_USER: querido
      MYSQL_PASSWORD: querido
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/1.sql:Z
    restart: unless-stopped